# Generated by Django 4.2.3 on 2023-07-17 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'Le nom du produit doit contenir au moins 3 charactères')])),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=4)),
                ('quantite', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'La  quantité de produit doit être égale ou supérieur à 0')])),
            ],
        ),
    ]
